package guzhijistudio.transfile.swing;

import guzhijistudio.transfile.utils.Config;
import javax.swing.JOptionPane;

public class ConfigDialog extends javax.swing.JDialog {

    private boolean saved;

    /**
     * Creates new form ConfigFrame
     */
    public ConfigDialog() {
        initComponents();

        if (Config.LOADED) {
            jTextFieldDeviceName.setText(Config.DEVICE_NAME);
            jTextFieldGroupAddr.setText(Config.GROUP_ADDR);
            jTextFieldDir.setText(Config.DIR);
        } else {
            jTextFieldDeviceName.setText("");
            jTextFieldGroupAddr.setText("224.0.0.255");
            jTextFieldDir.setText("");
        }

        saved = false;
    }

    public boolean isSaved() {
        return saved;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelDeviceName = new javax.swing.JLabel();
        jTextFieldDeviceName = new javax.swing.JTextField();
        jLabelGroupAddr = new javax.swing.JLabel();
        jTextFieldGroupAddr = new javax.swing.JTextField();
        jLabelDir = new javax.swing.JLabel();
        jTextFieldDir = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("guzhijistudio/transfile/swing/Bundle"); // NOI18N
        setTitle(bundle.getString("ConfigDialog.title")); // NOI18N
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        jLabelDeviceName.setLabelFor(jTextFieldDeviceName);
        jLabelDeviceName.setText(bundle.getString("ConfigDialog.jLabelDeviceName.text")); // NOI18N

        jTextFieldDeviceName.setMinimumSize(new java.awt.Dimension(100, 27));
        jTextFieldDeviceName.setPreferredSize(new java.awt.Dimension(100, 27));

        jLabelGroupAddr.setLabelFor(jTextFieldGroupAddr);
        jLabelGroupAddr.setText(bundle.getString("ConfigDialog.jLabelGroupAddr.text")); // NOI18N

        jTextFieldGroupAddr.setMinimumSize(new java.awt.Dimension(100, 27));
        jTextFieldGroupAddr.setPreferredSize(new java.awt.Dimension(100, 27));

        jLabelDir.setLabelFor(jTextFieldDir);
        jLabelDir.setText(bundle.getString("ConfigDialog.jLabelDir.text")); // NOI18N

        jTextFieldDir.setMinimumSize(new java.awt.Dimension(100, 27));
        jTextFieldDir.setPreferredSize(new java.awt.Dimension(100, 27));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDeviceName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelGroupAddr, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldGroupAddr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldDeviceName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelDeviceName)
                    .addComponent(jTextFieldDeviceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldGroupAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGroupAddr))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jButtonSave.setText(bundle.getString("ConfigDialog.jButtonSave.text")); // NOI18N
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSave);

        jButtonCancel.setText(bundle.getString("ConfigDialog.jButtonCancel.text")); // NOI18N
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancel);

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed

        Config.DEVICE_NAME = jTextFieldDeviceName.getText();
        Config.GROUP_ADDR = jTextFieldGroupAddr.getText();
        Config.DIR = jTextFieldDir.getText();
        if (Config.save()) {
            saved = true;
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "配置保存失败");
            System.exit(1);
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed

        dispose();

    }//GEN-LAST:event_jButtonCancelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelDeviceName;
    private javax.swing.JLabel jLabelDir;
    private javax.swing.JLabel jLabelGroupAddr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldDeviceName;
    private javax.swing.JTextField jTextFieldDir;
    private javax.swing.JTextField jTextFieldGroupAddr;
    // End of variables declaration//GEN-END:variables
}
