package guzhijistudio.transfile.swing;

public class FileItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form FileItemPanel
     */
    public FileItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelFileName = new javax.swing.JLabel();
        jLabelFileSize = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jLabelFileName.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabelFileName.setText("jLabel1");
        add(jLabelFileName);

        jLabelFileSize.setText("jLabel2");
        add(jLabelFileSize);
        add(jProgressBar1);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFileName;
    private javax.swing.JLabel jLabelFileSize;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
