package guzhijistudio.transfile.swing;

import java.awt.Dialog;
import javax.swing.JDialog;

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelSend = new javax.swing.JPanel();
        jPanelSendToolBar = new javax.swing.JPanel();
        jButtonAddFile = new javax.swing.JButton();
        jButtonSendAll = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        fileItemPanel1 = new guzhijistudio.transfile.swing.FileItemPanel();
        fileItemPanel2 = new guzhijistudio.transfile.swing.FileItemPanel();
        jPanelReceive = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        fileItemPanel3 = new guzhijistudio.transfile.swing.FileItemPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSend = new javax.swing.JMenu();
        jMenuItemAddFile = new javax.swing.JMenuItem();
        jMenuItemSendAll = new javax.swing.JMenuItem();
        jMenuConfig = new javax.swing.JMenu();
        jMenuItemConfig = new javax.swing.JMenuItem();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("guzhijistudio/transfile/swing/Bundle"); // NOI18N
        jMenuItem4.setText(bundle.getString("MainFrame.jMenuItem4.text")); // NOI18N
        jPopupMenu1.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("MainFrame.title")); // NOI18N
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(350, 2147483647));
        setMinimumSize(new java.awt.Dimension(350, 500));
        setPreferredSize(new java.awt.Dimension(350, 500));
        setResizable(false);

        jPanelSend.setLayout(new javax.swing.BoxLayout(jPanelSend, javax.swing.BoxLayout.PAGE_AXIS));

        jPanelSendToolBar.setLayout(new javax.swing.BoxLayout(jPanelSendToolBar, javax.swing.BoxLayout.LINE_AXIS));

        jButtonAddFile.setText(bundle.getString("MainFrame.jButtonAddFile.text")); // NOI18N
        jButtonAddFile.setFocusable(false);
        jButtonAddFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanelSendToolBar.add(jButtonAddFile);

        jButtonSendAll.setText(bundle.getString("MainFrame.jButtonSendAll.text")); // NOI18N
        jButtonSendAll.setFocusable(false);
        jButtonSendAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSendAll.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonSendAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendAllActionPerformed(evt);
            }
        });
        jPanelSendToolBar.add(jButtonSendAll);

        jPanelSend.add(jPanelSendToolBar);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel3.add(fileItemPanel1);
        jPanel3.add(fileItemPanel2);

        jScrollPane1.setViewportView(jPanel3);

        jPanelSend.add(jScrollPane1);

        jTabbedPane1.addTab(bundle.getString("MainFrame.jPanelSend.TabConstraints.tabTitle"), jPanelSend); // NOI18N

        jPanelReceive.setLayout(new javax.swing.BoxLayout(jPanelReceive, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.PAGE_AXIS));
        jPanel4.add(fileItemPanel3);

        jScrollPane2.setViewportView(jPanel4);

        jPanelReceive.add(jScrollPane2);

        jTabbedPane1.addTab(bundle.getString("MainFrame.jPanelReceive.TabConstraints.tabTitle"), jPanelReceive); // NOI18N
        jPanelReceive.getAccessibleContext().setAccessibleName(bundle.getString("MainFrame.jPanelReceive.AccessibleContext.accessibleName")); // NOI18N

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        jMenuSend.setText(bundle.getString("MainFrame.jMenuSend.text")); // NOI18N

        jMenuItemAddFile.setText(bundle.getString("MainFrame.jMenuItemAddFile.text")); // NOI18N
        jMenuSend.add(jMenuItemAddFile);

        jMenuItemSendAll.setText(bundle.getString("MainFrame.jMenuItemSendAll.text")); // NOI18N
        jMenuSend.add(jMenuItemSendAll);

        jMenuBar1.add(jMenuSend);

        jMenuConfig.setText(bundle.getString("MainFrame.jMenuConfig.text")); // NOI18N

        jMenuItemConfig.setText(bundle.getString("MainFrame.jMenuItemConfig.text")); // NOI18N
        jMenuItemConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConfigActionPerformed(evt);
            }
        });
        jMenuConfig.add(jMenuItemConfig);

        jMenuBar1.add(jMenuConfig);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConfigActionPerformed
        new ConfigFrame().setVisible(true);
    }//GEN-LAST:event_jMenuItemConfigActionPerformed

    private void jButtonSendAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendAllActionPerformed
        JDialog dialog = new JDialog(this, Dialog.ModalityType.APPLICATION_MODAL);
        dialog.setContentPane(new DeviceListPanel());
        dialog.setLocationByPlatform(true);
        dialog.setResizable(false);
        dialog.pack();
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonSendAllActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private guzhijistudio.transfile.swing.FileItemPanel fileItemPanel1;
    private guzhijistudio.transfile.swing.FileItemPanel fileItemPanel2;
    private guzhijistudio.transfile.swing.FileItemPanel fileItemPanel3;
    private javax.swing.JButton jButtonAddFile;
    private javax.swing.JButton jButtonSendAll;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConfig;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAddFile;
    private javax.swing.JMenuItem jMenuItemConfig;
    private javax.swing.JMenuItem jMenuItemSendAll;
    private javax.swing.JMenu jMenuSend;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelReceive;
    private javax.swing.JPanel jPanelSend;
    private javax.swing.JPanel jPanelSendToolBar;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
